package com.redhat.weightwatcher;

import com.redhat.weightwatcher.Goal;
com.redhat.weightwatcher.Fact( )
rule "ruleInsertGoal"
	salience 10000
when
    	fact : Fact( factname == "Goal" )
then
        

        Integer userid = "ABC";
       	String goalname = "weight";
        Integer target = 78;
        Integer start = 99;
        Integer low = 88;
        Integer high = 98;


    	Goal goal = new Goal(  );
	    goal.setUserid( userid );
	    goal.setGoalname( goalname );
	    goal.setTarget( target );
	    goal.setStart( start );
	    goal.setLow( low );

    	insert( goal );

    	System.out.println("==>weightwatcher " + drools.getRule( ).getName( ) + "->" + 
					goal.getUserid( )  + ":" + goal.getGoalname( ) );
end

query "getGoal"
	goal : Goal( )
end
