package com.redhat.weightwatcher;


import java.util.Date; 
import java.text.SimpleDateFormat;
import com.redhat.weightwatcher.Observation;

rule "ruleInsertObservation"
	salience 10000
when
    fact : Fact( factname == "Observation" )
then
    
    Integer userid = "ABC";
    SimpleDateFormat factSDF = new SimpleDateFormat("yyyy-M-d HH:mm:ss zzz");
    Date obsdate = factSDF.parse( "2016-05-23 12:67:55 EST" );
    Integer obsvalue = 92;
    String obsname = "weight";

    Observation observation = new Observation( );
    observation.setUserid( userid );
    observation.setObsname( obsname );
	observation.setObsdate ( obsdate );
	observation.setObsvalue( obsvalue ); 
    insert( observation );

    print("==>weightwatcher " + drools.getRule( ).getName( ) + "->" + 
	observation.getUserid( )  + ":" + observation.getObsname( ) + ":" + observation.getObsdate( ) );
end

query "getObservation"
	observation : Observation( )
end