package com.redhat.weightwatcher;



rule "ruleInsertParticipant"
	salience 10000
when
    fact : Fact( factname == "Participant" )
then
    
    Integer userid = "ABC";
    String username = "clin@redhat";
    
    Participant participant = new Participant( userid, username );
    insert( participant );
	System.out.println("==>username=" + username);
    System.out.println("==>weightwatcher " + drools.getRule( ).getName( ) + "->" + 
		participant.getUserid( )  + ":" + participant.getUsername( ) );
end

query "getParticipant"
	participant : Participant( )
end